### ISSUE TITLE
Идеи заданий (в основном для микромаппинга)

### ISSUE THREAD

**Issue by alexander-ii** [Zverik/osmstreak#19]
По желанию можно сгруппировать в одно: нарисовать по 5 каждого. Или не сгруппировывать, и тогда по 5+.

**полезное:**
- почтовые ящики (их, кажется, не особо мапят) `amenity=post_box`
- место отдыха (обычно вдоль трасс) `highway=rest_area`
- питьевая вода `amenity=drinking_water`

**интересное:**
- уличные фонари `highway=street_lamp`
- урны `amenity=waste_basket` + мусорные баки `amenity=waste_disposal`
- скамейки `amenity=bench`
- железнодорожная стрелка `railway=switch`

**прочее:**
- дорожное зеркало `highway=traffic_mirror`
- флагшток `man_made=flagpole`
- часы `amenity=clock`
- крышка люка `manhole=yes`
- камера наблюдения `man_made=surveillance` + `surveillance:type=camera`

**Comment by tohaklim** [comment]
I can do some of those if Zverik considers them suitable

**Comment by Zverik** [comment]
Thanks for your ideas Alexander! Some of these would be a good fit for OSM Streak, like railway switches or benches.

The principle and the single criteria for tasks is this: it must be doable by virtually any mapper anywhere on Earth in at most five minutes. We encourage people to open an editor by giving them tasks that they don't have to prepare for. "Oh, that's fun and I can do that in a minute" — and a changeset is submitted.

So, suitable are generic tasks which do not require, for example, going outside and surveying, or spending half an hour studying imagery and street view photos. Manholes are hard to find in rural areas. Clocks, mirrors and post boxes are invisible on imagery and people don't generally remember them, and it would be hard to find a new one for every mapper participating. Highway rest areas are too few, and too scarce to find an unmapped one in five minutes.

Of these, I find suitable these types:
* street lamps — because most cities and towns and villages have these, and almost none are mapped.
* railway switches — because that does not require imagery or going anywhere, any railway branching calls for a switch. The same for buffer stops.

Also barely make it:

* benches — while absent in villages, one usually knows a location of a few. And we can point to Mapillary of some city for a few pointers. The same for waste baskets.

**Comment by Zverik** [comment]
Added three good tasks from here. Thanks!
