### ISSUE TITLE
explicitly discourage globe-spanning changesets

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/osmstreak#38]
Apparently one of challenges encourages (or not discourages) using absurdly-large changeset bounding boxes.

Can it be tweaked to reduce risks of creating changesets editing completely unrelated objects?

Triggered by https://www.openstreetmap.org/changeset/59996441

**Comment by kartonage** [comment]
Recently encountered this with https://www.openstreetmap.org/changeset/68222102

> Want to do some mapping and continue your streak? Here is an idea:
>✈️ Around the World in Five Minutes
>Let's create a changeset with an enormous bounding box. Map something first in [https://www.openstreetmap.org/#map=5/-48.487/-69.895 South Chile], and then in [https://www.openstreetmap.org/#map=6/55.912/159.335 Kamchatka].
>When done, please head to http://streak.osmz.ru and click on the latest changeset.
>Yours, 
>OSM Streak

I would argue that this encourages to directly create the largest bounding boxes possible. 
There is no benefit to group unrelated objects together and it incentivises bad mapping practise.

While the edits are presumably in good faith it's still rather pointless and makes them harder to verify/identify for other mappers.

**Comment by Zverik** [comment]
Again, make that thought into an excercise on coming up with a better validation process, which won't be affected by bigger bboxes.

**Comment by matkoniecz** [comment]
For start please remove this task as it is actively harmful.

**Comment by matkoniecz** [comment]
Require not single changeset, but allow edits to be done in multiple ones.

Or even better, test multiple changesets and require that bounding box be within 100km.

**Comment by Zverik** [comment]
This task is not harmful, since it produces valid data. All complaints come from people who use flawed validation techniques based on assumptions OSM proves wrong again and again. If your tool just said "Added a building in Chile and another one in Kamchatka", you wouldn't look twice at it. Instead you are trying to shape OSM in the form of osmcha or whatever you are using. This task only highlights the flaw, but thousands of changesets go unchecked with it, because the flaw is less obvious with these. All I do and write is directed at making OSM better, and I can never understand people who want it to stay the same, to do nothing and pretend everything is well.

Also, tasks are not mandatory, they are just suggestions, left to discretion of users. If somebody agrees that making big changesets is wrong, they can easily skip this and make a different edit.

**Comment by matkoniecz** [comment]
> Instead you are trying to shape OSM in the form of osmcha or whatever you are using. 

I am using history tab at the main OSM site. Can you recommend a better tool that is accessible online for listing recent changes within a given area?

For example see https://www.openstreetmap.org/history#map=7/-51.973/-59.569

**Comment by Zverik** [comment]
Try https://simon04.dev.openstreetmap.org/whodidit/

**Comment by SomeoneElseOSM** [comment]
We're still seeing globe-wide bounding boxes created by users of this site.  In a recent example, a user at https://www.openstreetmap.org/changeset/79796071 knew that globe-wide bounding boxes were a bad idea, but did it because this site explicitly requested it.

@Zverik Why do you think that it is a good idea to encourage the creation of these?

**Comment by alexriabtsev** [comment]
> We're still seeing globe-wide bounding boxes created by users of this site. In a recent example, a user at https://www.openstreetmap.org/changeset/79796071 knew that globe-wide bounding boxes were a bad idea, but did it because this site explicitly requested it.
> 
> @Zverik Why do you think that it is a good idea to encourage the creation of these?

yeah, there would be better idea to encourage hotosm tasks to be done (PS I scanned through the tasks and found one about hotosm validation but not completing tasks)

**Comment by Mannivu** [comment]
It could be also removed in favour of a Maproulette task.

**Comment by matkoniecz** [comment]
Would you accept PR removing harmful https://github.com/Zverik/osmstreak/blob/master/tasks/3_around_the_world.yaml ?

**Comment by Zverik** [comment]
I doubt it. It is not harmful. The map gets better with this task. It's your tools that impose arbitrary restrictions on metadata. Please make instead a PR to the tool you're using to fix processing of such changesets. That was the idea.

**Comment by matkoniecz** [comment]
So you think that putting unrelated changes in worldwide changeset is perfectly fine?

**Comment by Zverik** [comment]
They are not unrelated. A changeset groups by no other criteria than intention. Most of the times the intention is geographically compact. Sometimes it isn't. When I click "History" on any given location of the map, I see many, too many globe-spanning changesets. Most of them I trust, since the intention for these is written in a comment. I trust mappers who do this five-minute task, because they are good enough mappers to know this website and complete its tasks. They also refer to the website when doing this, so you know the intention.

There is absolutely nothing wrong coming out of this task. The only reason you're here is that here you've got a point of contact. Unlike for thousands other big changesets, which you have to accept.

**Comment by matkoniecz** [comment]
> A changeset groups by no other criteria than intention.

Yes, and in rare cases it makes sense to make worldwide spanning changesets (like museum ship getting relocated across world or something).

But 

> Map something first in [https://www.openstreetmap.org/#map=5/-48.487/-69.895 South Chile], and then in [https://www.openstreetmap.org/#map=6/55.912/159.335 Kamchatka].

is encouraging to make unrelated changes across world without good reason.

**Comment by Zverik** [comment]
Why a mapper cannot map without a good reason?

Why do you take "unrelated changes across the world" as something bad without questioning it? In this entire thread, you and others just say it's bad, but finding reasons and proving the opposite somehow falls on me. Usually it's the other way around: you prove something is harmful with evidence, and then an action is taken.

**Comment by matkoniecz** [comment]
1) putting unrelated changes together creates changeset with unrelated changes

2) it breaks existing tools for handling changests

3) it encourages merging in one changeset unrelated changes

**Comment by matkoniecz** [comment]
> Why a mapper cannot map without a good reason?

I have no problem with armchair mapping Chile and then immediately armchair mapping Kamchatka.

I have problem with saving both changes in one changeset.

I have even problem with deliberately encouraging this and presenting it as a fun challenge. Yes, it would be nice to have smarter changeset handling tools. No, we don't have them at this moment.

**Comment by MoiraPrime** [comment]
The year is 2021 and this task is still causing issues.

**Comment by mikelmaron** [comment]
Congrats @Zverik — you’ve done something here that has me agreeing with @matkoniecz ;)

**Comment by Zverik** [comment]
Okay I'll do it this week. Weird how in three years forbidding harmless changesets is still easier than changing one piece of software that cannot process them based on some internal assumptions.

**Comment by matkoniecz** [comment]
> than changing one piece of software that cannot process them

That is not just one piece of software - it is that bounding box is a reasonable initial heuristic trivial to implement. Detecting that change edits corners with no effect in the middle is quite tricky and not straightforward.

For start moving nodes in corners in some cases will affect middle and in some cases will not.

So any software will start from such heuristic, and smarter processing needs to be added at the cost of a very significant effort and vastly complicated processing and heavy performance impact. And one solution is not trivially portable to other systems.

> you’ve done something here that has me agreeing with @matkoniecz ;)

Thanks. At least I think so :)

**Comment by Zverik** [comment]
Done.
